name: Build Zola project and deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 1
        persist-credentials: false

    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v5
    
    - name: echo this repository's Pages domain
      run: echo "${{ steps.pages.outputs.base_url }}"
      
    - uses: taiki-e/install-action@v2
      with:
        tool: zola@0.22.1

    - name: Build the website
      run: zola build --base-url "${{ steps.pages.outputs.base_url }}"

    - name: Upload /public as an action artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: public

    - name: Deploy artifact to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

      
